### ISSUE TITLE
publications   paper

### ISSUE THREAD

**Issue by chumingqian** [yashmaniya0/Respiratory-Sound-Classification-with-BiGRU-and-BiLSTMs#1]
Hello, author.
             Do you have any relevant publications   paper  or other more specific blogs?

**Comment by yashmaniya0** [comment]
Hi @chumingqian,
Please find the research paper here : [Respiratory Sound Classification Based on BiGRU-Attention Network with XGBoost](https://ieeexplore.ieee.org/document/9313506)
